name: beamcoda_jobs_flutter
description: BeamCoda Jobs Portal Flutter Application

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  http: ^0.13.5
  device_info_plus: ^5.0.1
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  intl: ^0.17.0
  url_launcher: ^6.1.6
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  flutter_datetime_picker: ^1.5.1
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/illustrations/
    - assets/icons/
    - assets/icons/sharer/
    